
package Forms;

import Entity.Departement;
import company.Tools;

/**
 *
 * @author MOSTAPHA
 */
public class Form_Departement extends javax.swing.JFrame {

    /**
     * Creates new form Form_Departement
     */
    public Form_Departement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Txt_DeptNO = new controls.JTextBox(15);
        Txt_DeptName = new controls.JTextBox(15);
        Txt_DeptLocation = new controls.JTextBox(15);
        Btn_Update = new controls.JMyButton();
        Btn_Delete = new controls.JMyButton();
        Btn_Find = new controls.JMyButton();
        Btn_All = new controls.JMyButton();
        Btn_Clear = new controls.JMyButton();
        Btn_back = new controls.JMyButton();
        Btn_Add = new controls.JMyButton();
        jLabel5 = new javax.swing.JLabel();
        Rdo_Number = new javax.swing.JRadioButton();
        Rdo_Location = new javax.swing.JRadioButton();
        Rdo_Name = new javax.swing.JRadioButton();
        Txt_Search = new controls.JTextBox(15);
        Btn_Search = new controls.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Dept = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel1.setText("Département");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setText("Recherche par :");

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setText("Local du département");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel4.setText("Nom du département");

        Txt_DeptNO.setEditable(false);
        Txt_DeptNO.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Txt_DeptName.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_DeptName.setText("   ");
        Txt_DeptName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DeptNameActionPerformed(evt);
            }
        });

        Txt_DeptLocation.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_DeptLocation.setText("   ");
        Txt_DeptLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DeptLocationActionPerformed(evt);
            }
        });

        Btn_Update.setText("Modifier");
        Btn_Update.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Delete.setText("Supprimer");
        Btn_Delete.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_Find.setText("Afficher Dépt");
        Btn_Find.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FindActionPerformed(evt);
            }
        });

        Btn_All.setText("Afficher Tous");
        Btn_All.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AllActionPerformed(evt);
            }
        });

        Btn_Clear.setText("Vider");
        Btn_Clear.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });

        Btn_back.setText("Retour");
        Btn_back.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        Btn_Add.setText("Ajouter");
        Btn_Add.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setText("Numéro du département");

        Rdo_Number.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Number.setSelected(true);
        Rdo_Number.setText("Numéro");
        Rdo_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_NumberActionPerformed(evt);
            }
        });

        Rdo_Location.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Location.setText("Local");
        Rdo_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_LocationActionPerformed(evt);
            }
        });

        Rdo_Name.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name.setText("Nom");
        Rdo_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_NameActionPerformed(evt);
            }
        });

        Txt_Search.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Btn_Search.setText("Recherche");
        Btn_Search.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        Table_Dept.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Table_Dept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Dépt", "Nom Dépt", "Local dépt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Dept.setToolTipText("");
        Table_Dept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_DeptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Dept);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 623, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addComponent(Rdo_Number)
                        .addGap(43, 43, 43)
                        .addComponent(Rdo_Name)
                        .addGap(66, 66, 66)
                        .addComponent(Rdo_Location))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_DeptName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(Txt_DeptNO)
                                    .addComponent(Txt_DeptLocation)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Txt_Search)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Rdo_Number)
                    .addComponent(Rdo_Location)
                    .addComponent(Rdo_Name))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_DeptNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txt_DeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Txt_DeptLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rdo_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_NumberActionPerformed

    private void Rdo_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_LocationActionPerformed

    private void Rdo_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_NameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
         Btn_Group.add(Rdo_Number);
         Btn_Group.add(Rdo_Name);
         Btn_Group.add(Rdo_Location);
         
         Clear_Data();
         dept.Get_All_Rows(Table_Dept);
         
         Table_Dept.getTableHeader().setReorderingAllowed(false);
        
         
        
    }//GEN-LAST:event_formWindowOpened

    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed
        this.dispose();
        Tools.OpenForm(new Form_Main());
    }//GEN-LAST:event_Btn_backActionPerformed

    Departement dept = new Departement();
    
    private void Clear_Data()
    {
        Tools.ClearText(this);
        Txt_DeptNO.setText(dept.Get_Auto_Number());
        
        Btn_Add.setEnabled(true);
        Btn_Update.setEnabled(false);
        Btn_Delete.setEnabled(false);
        
        Txt_DeptName.requestFocus();
    }
//--------------------------------------------------------------------------------------
    private void Set_Values()
    {
        int D_NO = Integer.parseInt(Txt_DeptNO.getText());
        String D_Name = Txt_DeptName.getText();
        String D_Location = Txt_DeptLocation.getText();
        

        dept.setDept_NO(D_NO);
        dept.setDept_Name(D_Name);
        dept.setLocation(D_Location);
        
        
    }    
    
    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
         Clear_Data();
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Txt_DeptLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DeptLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DeptLocationActionPerformed

    private void Txt_DeptNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DeptNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DeptNameActionPerformed


    
    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        
        Set_Values();
        dept.Add();
        Clear_Data();
        dept.Get_All_Rows(Table_Dept);
        
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
     
        Set_Values();
        dept.Update();
        Clear_Data();
        dept.Get_All_Rows(Table_Dept);
        
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        if(Tools.Confirm_Msg(" Voulez vous vraiment supprimer le Département ?! "))
        {    
            Set_Values();
            dept.Delete();
            Clear_Data();
            dept.Get_All_Rows(Table_Dept);
        }
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FindActionPerformed
        
        String Str_DeptNO = (String)Tools.InputBox(" Veillez saisir le numéro du Département !");
        int DeptNO = Integer.parseInt(Str_DeptNO);
        
        dept.setDept_NO(DeptNO);
        dept.Get_One_Row(Table_Dept);
        
    }//GEN-LAST:event_Btn_FindActionPerformed

    private void Btn_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AllActionPerformed
        
        dept.Get_All_Rows(Table_Dept);
        
    }//GEN-LAST:event_Btn_AllActionPerformed

    private void Table_DeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_DeptMouseClicked
        try
        {
            int row = Table_Dept.getSelectedRow();
            
            String Str_Number =Table_Dept.getValueAt(row, 0).toString();
            String Str_Name =Table_Dept.getValueAt(row, 1).toString();
            String Str_Local =Table_Dept.getValueAt(row, 2).toString();
            
            Txt_DeptNO.setText(Str_Number);
            Txt_DeptName.setText(Str_Name);
            Txt_DeptLocation.setText(Str_Local);
            
            Btn_Add.setEnabled(false);
            Btn_Update.setEnabled(true);
            Btn_Delete.setEnabled(true);
            
        }
        catch(Exception ex)
        {
            Tools.MsgBox(ex.getMessage());
        }
    }//GEN-LAST:event_Table_DeptMouseClicked

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        
        String Str_Search = "select * from departement_data where " ;
        
        if(Rdo_Number.isSelected())
        {
            Str_Search += "Departement_NO";
        }
        else if(Rdo_Name.isSelected())
        {
            Str_Search += "Departement";
        }
        else 
        {
            Str_Search += "Location";
        }
        
        Str_Search += " like '%" + Txt_Search.getText() +  "%' ;";
        
        dept.Get_Custom_Rows(Str_Search, Table_Dept);
        
        
    }//GEN-LAST:event_Btn_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Departement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Departement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Departement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Departement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Departement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton Btn_Add;
    private controls.JMyButton Btn_All;
    private controls.JMyButton Btn_Clear;
    private controls.JMyButton Btn_Delete;
    private controls.JMyButton Btn_Find;
    private javax.swing.ButtonGroup Btn_Group;
    private controls.JMyButton Btn_Search;
    private controls.JMyButton Btn_Update;
    private controls.JMyButton Btn_back;
    private javax.swing.JRadioButton Rdo_Location;
    private javax.swing.JRadioButton Rdo_Name;
    private javax.swing.JRadioButton Rdo_Number;
    private javax.swing.JTable Table_Dept;
    private javax.swing.JTextField Txt_DeptLocation;
    private javax.swing.JTextField Txt_DeptNO;
    private javax.swing.JTextField Txt_DeptName;
    private javax.swing.JTextField Txt_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
