
package Forms;

import Entity.Departement;
import Entity.Employee;
import Entity.Employee_Phones;
import company.Tools;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOSTAPHA
 */
public class Form_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Form_Employee
     */
    public Form_Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Group = new javax.swing.ButtonGroup();
        Btn_back = new controls.JMyButton();
        jLabel5 = new javax.swing.JLabel();
        Rdo_Number = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Txt_EmpAddress = new controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        Rdo_Dept = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Rdo_Name = new javax.swing.JRadioButton();
        Btn_Find = new controls.JMyButton();
        Txt_EmpSalary = new controls.JTextBox(15);
        jLabel10 = new javax.swing.JLabel();
        Txt_Search = new controls.JTextBox(15);
        Btn_All = new controls.JMyButton();
        Btn_Search = new controls.JMyButton();
        jLabel11 = new javax.swing.JLabel();
        Rdo_Birth = new javax.swing.JRadioButton();
        Txt_EmpNO = new controls.JTextBox(15);
        Rdo_Address = new javax.swing.JRadioButton();
        JDate_Birth = new com.toedter.calendar.JDateChooser();
        Rdo_Salary = new javax.swing.JRadioButton();
        JDate_Hiring = new com.toedter.calendar.JDateChooser();
        Combo_Dept = new controls.JMyCombo();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Emp = new javax.swing.JTable();
        Btn_Add = new controls.JMyButton();
        Btn_Update = new controls.JMyButton();
        Btn_Delete = new controls.JMyButton();
        Btn_Clear = new controls.JMyButton();
        Btn_Add_Dept = new controls.JMyButton();
        jLabel2 = new javax.swing.JLabel();
        Txt_EmpName = new controls.JTextBox(15);
        jLabel7 = new javax.swing.JLabel();
        Rdo_Hiring = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Contact = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        Txt_Contact = new controls.JTextBox(15);
        Btn_Add_Contact = new controls.JMyButton();
        Btn_Delete_Contacts = new controls.JMyButton();
        Rdo_Contact = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Btn_back.setText("Retour");
        Btn_back.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setText("Nom complet");

        Rdo_Number.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Number.setSelected(true);
        Rdo_Number.setText("ID");
        Rdo_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_NumberActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel6.setText("Adresse");

        Txt_EmpAddress.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_EmpAddress.setText("   ");
        Txt_EmpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmpAddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel8.setText("Date d 'embauche ");

        Rdo_Dept.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Dept.setText("Dépt");
        Rdo_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_DeptActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel9.setText("Date de naissance");

        Rdo_Name.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name.setText("Nom");
        Rdo_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_NameActionPerformed(evt);
            }
        });

        Btn_Find.setText("Afficher un Employé");
        Btn_Find.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FindActionPerformed(evt);
            }
        });

        Txt_EmpSalary.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_EmpSalary.setText("   ");
        Txt_EmpSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmpSalaryActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel10.setText("Département");

        Txt_Search.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_SearchActionPerformed(evt);
            }
        });

        Btn_All.setText("Afficher Tous");
        Btn_All.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AllActionPerformed(evt);
            }
        });

        Btn_Search.setText("Recherche");
        Btn_Search.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel11.setText("Identifiant ");

        Rdo_Birth.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Birth.setText("D_Naissance");
        Rdo_Birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_BirthActionPerformed(evt);
            }
        });

        Txt_EmpNO.setEditable(false);
        Txt_EmpNO.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_EmpNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmpNOActionPerformed(evt);
            }
        });

        Rdo_Address.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Address.setText("Adresse");
        Rdo_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_AddressActionPerformed(evt);
            }
        });

        JDate_Birth.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Rdo_Salary.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Salary.setText("Salaire");
        Rdo_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_SalaryActionPerformed(evt);
            }
        });

        JDate_Hiring.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Combo_Dept.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel1.setText("Employé");

        Table_Emp.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Table_Emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom complet", "Adresse", "Salaire", "D_Embauche", "D_Naissance", "ID_Dept", "Département"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EmpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Emp);

        Btn_Add.setText("Ajouter");
        Btn_Add.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        Btn_Update.setText("Modifier");
        Btn_Update.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Delete.setText("Supprimer");
        Btn_Delete.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_Clear.setText("Vider ");
        Btn_Clear.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });

        Btn_Add_Dept.setText("+");
        Btn_Add_Dept.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        Btn_Add_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Add_DeptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setText("Recherche par :");

        Txt_EmpName.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_EmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_EmpNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel7.setText("Salaire");

        Rdo_Hiring.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Hiring.setText("D_Embauche");
        Rdo_Hiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_HiringActionPerformed(evt);
            }
        });

        Table_Contact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contacts "
            }
        ));
        Table_Contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ContactMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_Contact);

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel12.setText("Contact d'employé");

        Txt_Contact.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Txt_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ContactActionPerformed(evt);
            }
        });

        Btn_Add_Contact.setText("Ajouter un Contact");
        Btn_Add_Contact.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Add_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Add_ContactActionPerformed(evt);
            }
        });

        Btn_Delete_Contacts.setText("Vider le tableau");
        Btn_Delete_Contacts.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Delete_Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Delete_ContactsActionPerformed(evt);
            }
        });

        Rdo_Contact.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Contact.setText("Contact");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_All, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Find, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)))
                            .addComponent(Btn_Add_Dept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(28, 28, 28)
                                        .addComponent(Txt_Contact))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_Add_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Delete_Contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(777, 777, 777)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Rdo_Number)
                        .addGap(18, 18, 18)
                        .addComponent(Rdo_Name)
                        .addGap(18, 18, 18)
                        .addComponent(Rdo_Address)
                        .addGap(18, 18, 18)
                        .addComponent(Rdo_Salary)
                        .addGap(18, 18, 18)
                        .addComponent(Rdo_Hiring)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rdo_Birth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rdo_Dept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rdo_Contact)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_EmpName)
                                    .addComponent(JDate_Hiring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(1145, 1145, 1145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(67, 67, 67)
                        .addComponent(Combo_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(69, 69, 69)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Txt_EmpSalary)
                        .addComponent(JDate_Birth, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addComponent(Txt_EmpAddress)
                        .addComponent(Txt_EmpNO))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdo_Number)
                    .addComponent(Rdo_Name)
                    .addComponent(Rdo_Address)
                    .addComponent(Rdo_Salary)
                    .addComponent(Rdo_Hiring)
                    .addComponent(Rdo_Birth)
                    .addComponent(Rdo_Dept)
                    .addComponent(Rdo_Contact))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(Txt_EmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(JDate_Hiring, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Combo_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Add_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Txt_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Delete_Contacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Add_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(198, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Txt_EmpNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(200, 200, 200)
                                    .addComponent(JDate_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(Txt_EmpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(Txt_EmpSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(292, 292, 292))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(66, 66, 66)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(151, 151, 151)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Departement dept2 =  new Departement();
    Employee emp = new Employee();
    Employee_Phones phones =new Employee_Phones();
    
//-----------------------------------------------------------------------------------------    
    private void Clear_Data()
    {
        Tools.ClearText(this);
        Txt_EmpNO.setText(emp.Get_Auto_Number());
        
        Btn_Add.setEnabled(true);
        Btn_Update.setEnabled(false);
        Btn_Delete.setEnabled(false);
        
        Clear_Contacts();
       //Btn_Delete_ContactsActionPerformed(null); // --> appellation seulement de l'action du bouton Btn_Delete_Contacts
                                                        // qui va vider le contenu du Tableau contact
        
        Txt_EmpName.requestFocus();
    }
 //---------------------------------------------------------------------------------------------
        private void Clear_Contacts()
        {
               
            DefaultTableModel model =(DefaultTableModel)Table_Contact.getModel();
            model.setNumRows(0);
            
        }
  //---------------------------------------------------------------------------------------------
        private void Set_Values()
    {
        emp.setEmp_NO(Integer.parseInt(Txt_EmpNO.getText()));
        emp.setEmp_Name(Txt_EmpName.getText());
        emp.setAddress(Txt_EmpAddress.getText());
        emp.setSalary(Double.parseDouble(Txt_EmpSalary.getText()));
        
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String H_Date = String.valueOf(f.format(JDate_Hiring.getDate()));
        String B_Date = String.valueOf(f.format(JDate_Birth.getDate()));
        
        emp.setHiring_Date(H_Date);
        emp.setBirth_Date(B_Date);
        
        String D_Name = Combo_Dept.getSelectedItem().toString(); // cherchons Dept_NO on donnant le nom du departement
        String D_NO = dept2.GetValue_By_Name(D_Name);
        
        emp.setDept_NO(Integer.parseInt(D_NO));
    }
    
    
   
    
    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed
        
        this.dispose();
        Tools.OpenForm(new Form_Main());
        
    }//GEN-LAST:event_Btn_backActionPerformed

    private void Rdo_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_NumberActionPerformed

    private void Txt_EmpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmpAddressActionPerformed

    private void Rdo_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_DeptActionPerformed

    private void Rdo_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_NameActionPerformed

    private void Btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FindActionPerformed

        String Str_EmpNO = (String)Tools.InputBox(" Veillez saisir l'Identifiant de l'employé !");
        int EnpNO = Integer.parseInt(Str_EmpNO);

        emp.setEmp_NO(EnpNO);
        emp.Get_One_Row(Table_Emp);
       
    }//GEN-LAST:event_Btn_FindActionPerformed

    private void Txt_EmpSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmpSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmpSalaryActionPerformed

    private void Txt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_SearchActionPerformed

    private void Btn_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AllActionPerformed

       emp.Get_All_Rows(Table_Emp);
       
    }//GEN-LAST:event_Btn_AllActionPerformed

    private String Get_My_LikeQuery()
    {
        
        return " like'%" + Txt_Search.getText() +  "%'" ;
    }
    
    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed

        String Str_Search = "select * from employee_data where " ;

        if(Rdo_Number.isSelected())
        {
            Str_Search += "Number " + Get_My_LikeQuery();
        }
        else if(Rdo_Name.isSelected())
        {
            Str_Search += "Name " + Get_My_LikeQuery() ;
        }
        else if(Rdo_Address.isSelected())
        {
            Str_Search += "Address " + Get_My_LikeQuery() ;
        }
        else if(Rdo_Salary.isSelected())
        {
            Str_Search += "Salary " + Get_My_LikeQuery() ;
        }
        else if(Rdo_Hiring.isSelected())
        {
            Str_Search += "Hiring_Date " + Get_My_LikeQuery() ;
        }
        else if(Rdo_Birth.isSelected())
        {
            Str_Search += "Date_Of_Birth " + Get_My_LikeQuery() ;
        }
        else if(Rdo_Dept.isSelected())
        {
            Str_Search += "Departement_NO "  + Get_My_LikeQuery() +
                            " or Departement " + Get_My_LikeQuery() ;
        }
        else
        {
            String STR_EMPNO =phones.Get_EmpNO_By_Phone(Txt_Search.getText());
            
            Str_Search += " Number like '%"+ STR_EMPNO +"%' ;" ;
        }

        emp.Get_Custom_Rows(Str_Search, Table_Emp);
        
    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void Rdo_BirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_BirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_BirthActionPerformed

    private void Txt_EmpNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmpNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmpNOActionPerformed

    private void Rdo_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_AddressActionPerformed

    private void Rdo_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_SalaryActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed

        Set_Values();
        emp.Add();
         
        // Add phones
        phones.setEmp_NO(Integer.parseInt(Txt_EmpNO.getText()));
        for(int x=0; x<Table_Contact.getRowCount() ; x++)
        {
            phones.setPhone(Table_Contact.getValueAt(x, 0).toString());
            phones.Add();
        }
        
        Clear_Data();
        emp.Get_All_Rows(Table_Emp);
        
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed

        Set_Values();
        emp.Update();
        
        // Phones
        phones.setEmp_NO(Integer.parseInt(Txt_EmpNO.getText()));
        phones.Delete_By_emp(); // supprimer les anciens contacts pour faire un Update 
        
        // Add news contact
        for(int x=0; x<Table_Contact.getRowCount() ; x++)
        {
            phones.setPhone(Table_Contact.getValueAt(x, 0).toString());
            phones.Add();
        }
        
        
        Clear_Data();
        emp.Get_All_Rows(Table_Emp);
      
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        
        if(Tools.Confirm_Msg(" Voulez vous vraiment supprimer l'employé ?! "))
        {
        
            // supprimer les Phones avant de supprimer l employe
            phones.setEmp_NO(Integer.parseInt(Txt_EmpNO.getText()));
            phones.Delete_By_emp(); // supprimer
            
            // suppression employe
            Set_Values();
            emp.Delete();
            
            Clear_Data();
            emp.Get_All_Rows(Table_Emp);
        }
        
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
     
        Clear_Data();
        
    }//GEN-LAST:event_Btn_ClearActionPerformed

    
    private void Btn_Add_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Add_DeptActionPerformed
       
        int DeptNO =Integer.parseInt(dept2.Get_Auto_Number());
        String DeptName = (String)Tools.InputBox(" Saisir le nom du département !");
        String Location = (String)Tools.InputBox(" Saisir le local du département !");
        
        dept2.setDept_NO(DeptNO);
        dept2.setDept_Name(DeptName);
        dept2.setLocation(Location);
        
        dept2.Add();
        
        data_base.Go.Fill_Combo("departement", "DeptName", Combo_Dept);
        
        
    }//GEN-LAST:event_Btn_Add_DeptActionPerformed

    private void Txt_EmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_EmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_EmpNameActionPerformed

    private void Rdo_HiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_HiringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_HiringActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Btn_Group.add(Rdo_Number);
        Btn_Group.add(Rdo_Name);
        Btn_Group.add(Rdo_Address);
        Btn_Group.add(Rdo_Salary);
        Btn_Group.add(Rdo_Hiring);
        Btn_Group.add(Rdo_Birth);
        Btn_Group.add(Rdo_Dept);
        Btn_Group.add(Rdo_Contact);
        
        data_base.Go.Fill_Combo("departement", "DeptName", Combo_Dept);
        
        emp.Get_All_Rows(Table_Emp);
        
        Clear_Data();
        
        Table_Emp.getTableHeader().setReorderingAllowed(false);
        Table_Contact.getTableHeader().setReorderingAllowed(false);
          
    }//GEN-LAST:event_formWindowOpened

    private void Table_EmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EmpMouseClicked
        try
        {
             int row = Table_Emp.getSelectedRow();
            
            String Str_Number =Table_Emp.getValueAt(row, 0).toString();
            String Str_Name =Table_Emp.getValueAt(row, 1).toString();
            String Str_Address =Table_Emp.getValueAt(row, 2).toString();
            String Str_Salary =Table_Emp.getValueAt(row, 3).toString();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date Hi_Date = sdf.parse(Table_Emp.getValueAt(row, 4).toString() );
            Date Br_Date = sdf.parse(Table_Emp.getValueAt(row, 5).toString() );
            
           // String Str_Dept = Table_Emp.getValueAt(row, 6).toString();
            
            Txt_EmpNO.setText(Str_Number);
            Txt_EmpName.setText(Str_Name);
            Txt_EmpAddress.setText(Str_Address);
            Txt_EmpSalary.setText(Str_Salary);
            
            JDate_Hiring.setDate(Hi_Date);
            JDate_Birth.setDate(Br_Date);
            
            Combo_Dept.setSelectedItem(Table_Emp.getValueAt(row, 7)); // '7' ? : apres la selection d'une ligne du tableau 
                                                                     //  On veux afficher sur le combo le nom du 
                                                                    // departement et non pas son ID
            //affichage des contacts de l employe sur le tableau de contacts apres une selection par la souris 
            // sur le tableau Table_Emp
            phones.setEmp_NO(Integer.parseInt(Txt_EmpNO.getText()));
            phones.Get_All_Rows(Table_Contact);
            
                                                                  
            Btn_Add.setEnabled(false);
            Btn_Update.setEnabled(true);
            Btn_Delete.setEnabled(true);
            
            
        }
        catch(Exception ex)
        {
            Tools.MsgBox(ex.getMessage());
        }
        
    }//GEN-LAST:event_Table_EmpMouseClicked

    private void Txt_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ContactActionPerformed

    private void Btn_Add_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Add_ContactActionPerformed
     
        DefaultTableModel model =(DefaultTableModel)Table_Contact.getModel();
        model.addRow(new Object[]{Txt_Contact.getText()});
        Txt_Contact.setText("");
        Txt_Contact.requestFocus();
    }//GEN-LAST:event_Btn_Add_ContactActionPerformed

    private void Btn_Delete_ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Delete_ContactsActionPerformed
        
        Clear_Contacts();
        
        
        /* 
            on peut utiliser aussi ce code: avec une appellation de ce bouton dans la methode Clear_Data()
        
        DefaultTableModel model =(DefaultTableModel)Table_Contact.getModel();
        model.setNumRows(0);
        
        */  
        
    }//GEN-LAST:event_Btn_Delete_ContactsActionPerformed

    private void Table_ContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ContactMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_ContactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton Btn_Add;
    private controls.JMyButton Btn_Add_Contact;
    private controls.JMyButton Btn_Add_Dept;
    private controls.JMyButton Btn_All;
    private controls.JMyButton Btn_Clear;
    private controls.JMyButton Btn_Delete;
    private controls.JMyButton Btn_Delete_Contacts;
    private controls.JMyButton Btn_Find;
    private javax.swing.ButtonGroup Btn_Group;
    private controls.JMyButton Btn_Search;
    private controls.JMyButton Btn_Update;
    private controls.JMyButton Btn_back;
    private controls.JMyCombo Combo_Dept;
    private com.toedter.calendar.JDateChooser JDate_Birth;
    private com.toedter.calendar.JDateChooser JDate_Hiring;
    private javax.swing.JRadioButton Rdo_Address;
    private javax.swing.JRadioButton Rdo_Birth;
    private javax.swing.JRadioButton Rdo_Contact;
    private javax.swing.JRadioButton Rdo_Dept;
    private javax.swing.JRadioButton Rdo_Hiring;
    private javax.swing.JRadioButton Rdo_Name;
    private javax.swing.JRadioButton Rdo_Number;
    private javax.swing.JRadioButton Rdo_Salary;
    private javax.swing.JTable Table_Contact;
    private javax.swing.JTable Table_Emp;
    private javax.swing.JTextField Txt_Contact;
    private javax.swing.JTextField Txt_EmpAddress;
    private javax.swing.JTextField Txt_EmpNO;
    private javax.swing.JTextField Txt_EmpName;
    private javax.swing.JTextField Txt_EmpSalary;
    private javax.swing.JTextField Txt_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
