
package Forms;

import Entity.Work_On;
import company.Tools;

/**
 *
 * @author MOSTAPHA
 */
public class Form_Report_WorkOn extends javax.swing.JFrame {

    /**
     * Creates new form Form_Report_WorkOn
     */
    public Form_Report_WorkOn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Group = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        Rdo_Num_Emp = new javax.swing.JRadioButton();
        Rdo_Name_Project = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Work_On = new javax.swing.JTable();
        Rdo_Num_Project = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Rdo_Name_Emp = new javax.swing.JRadioButton();
        Txt_Search = new controls.JTextBox(15);
        Btn_Search = new controls.JMyButton();
        Btn_All = new controls.JMyButton();
        Btn_Print = new controls.JMyButton();
        Btn_back = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setText("Recherche par :");

        Rdo_Num_Emp.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Num_Emp.setSelected(true);
        Rdo_Num_Emp.setText("Num. Emp.");
        Rdo_Num_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Num_EmpActionPerformed(evt);
            }
        });

        Rdo_Name_Project.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name_Project.setText("Nom. Projet");
        Rdo_Name_Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Name_ProjectActionPerformed(evt);
            }
        });

        Table_Work_On.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Table_Work_On.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro Employé", "Nom Employé", "Numéro Projet", "Nom Projet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Work_On.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_Work_OnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Work_On);

        Rdo_Num_Project.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Num_Project.setText("Num. Projet");
        Rdo_Num_Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Num_ProjectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setText("Rapport Work_On");

        Rdo_Name_Emp.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name_Emp.setText("Nom Emp.");
        Rdo_Name_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Name_EmpActionPerformed(evt);
            }
        });

        Txt_Search.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Btn_Search.setText("Recherche");
        Btn_Search.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        Btn_All.setText("Afficher Tous");
        Btn_All.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AllActionPerformed(evt);
            }
        });

        Btn_Print.setText("Imprimer");
        Btn_Print.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PrintActionPerformed(evt);
            }
        });

        Btn_back.setText("Retour");
        Btn_back.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(102, 102, 102)
                                .addComponent(Rdo_Num_Emp)
                                .addGap(124, 124, 124)
                                .addComponent(Rdo_Name_Emp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rdo_Num_Project)
                                .addGap(112, 112, 112)
                                .addComponent(Rdo_Name_Project))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(409, 409, 409))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(520, 520, 520))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdo_Num_Emp)
                    .addComponent(Rdo_Name_Emp)
                    .addComponent(jLabel2)
                    .addComponent(Rdo_Num_Project)
                    .addComponent(Rdo_Name_Project))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     Work_On wOn = new Work_On();
    
    private void Rdo_Num_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Num_EmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Num_EmpActionPerformed

    private void Rdo_Name_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Name_ProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Name_ProjectActionPerformed

    private void Table_Work_OnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_Work_OnMouseClicked

        
    }//GEN-LAST:event_Table_Work_OnMouseClicked

    private void Rdo_Num_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Num_ProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Num_ProjectActionPerformed

    private void Rdo_Name_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Name_EmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Name_EmpActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed

        String Str_Search = "select * from work_on_data where " ;

        if(Rdo_Num_Emp.isSelected())
        {
            Str_Search += "Number";
        }
        else if(Rdo_Name_Emp.isSelected())
        {
            Str_Search += "Name";
        }
        else if(Rdo_Num_Project.isSelected())
        {
            Str_Search += "Project_NO";
        }
        else
        {
            Str_Search += "Project_Name";
        }

        Str_Search += " like '%" + Txt_Search.getText() +  "%' ;";

        wOn.Get_Custom_Rows(Str_Search, Table_Work_On);

    }//GEN-LAST:event_Btn_SearchActionPerformed

   
    
    private void Btn_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AllActionPerformed

        wOn.Get_All_Rows(Table_Work_On);
        
    }//GEN-LAST:event_Btn_AllActionPerformed

    private void Btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PrintActionPerformed

        Tools.Print_Report(Table_Work_On, "Work_On");
        
    }//GEN-LAST:event_Btn_PrintActionPerformed

    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed

        this.dispose();
        Tools.OpenForm(new Form_Repports());

    }//GEN-LAST:event_Btn_backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
         Btn_Group.add(Rdo_Num_Emp);
         Btn_Group.add(Rdo_Name_Emp);
         Btn_Group.add(Rdo_Num_Project);
         Btn_Group.add(Rdo_Name_Project);
         
         wOn.Get_All_Rows(Table_Work_On);
        
          Tools.Set_Report(Table_Work_On);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Report_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Report_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Report_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Report_WorkOn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Report_WorkOn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton Btn_All;
    private javax.swing.ButtonGroup Btn_Group;
    private controls.JMyButton Btn_Print;
    private controls.JMyButton Btn_Search;
    private controls.JMyButton Btn_back;
    private javax.swing.JRadioButton Rdo_Name_Emp;
    private javax.swing.JRadioButton Rdo_Name_Project;
    private javax.swing.JRadioButton Rdo_Num_Emp;
    private javax.swing.JRadioButton Rdo_Num_Project;
    private javax.swing.JTable Table_Work_On;
    private javax.swing.JTextField Txt_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
