
package Forms;

import Entity.Employee;
import Entity.Project;
import Entity.Work_On;
import company.Tools;

/**
 *
 * @author MOSTAPHA
 */
public class Form_Work_On extends javax.swing.JFrame {

    /**
     * Creates new form Form_Work_On
     */
    public Form_Work_On() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Combo_Project = new controls.JMyCombo();
        Combo_Emp = new controls.JMyCombo();
        Btn_back = new controls.JMyButton();
        Btn_Add = new controls.JMyButton();
        Btn_Delete = new controls.JMyButton();
        Btn_Find = new controls.JMyButton();
        Btn_All = new controls.JMyButton();
        Rdo_Name_Emp = new javax.swing.JRadioButton();
        Txt_Search = new controls.JTextBox(15);
        Btn_Search = new controls.JMyButton();
        jLabel2 = new javax.swing.JLabel();
        Rdo_Num_Emp = new javax.swing.JRadioButton();
        Rdo_Name_Project = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Work_On = new javax.swing.JTable();
        Rdo_Num_Project = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel1.setText("Work_On");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setText("Projet");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel6.setText("Emplyé");

        Btn_back.setText("Retour");
        Btn_back.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        Btn_Add.setText("Ajouter");
        Btn_Add.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        Btn_Delete.setText("Supprimer");
        Btn_Delete.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_Find.setText("Afficher Work_On");
        Btn_Find.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FindActionPerformed(evt);
            }
        });

        Btn_All.setText("Afficher Tous");
        Btn_All.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AllActionPerformed(evt);
            }
        });

        Rdo_Name_Emp.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name_Emp.setText("Nom Emp.");
        Rdo_Name_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Name_EmpActionPerformed(evt);
            }
        });

        Txt_Search.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        Btn_Search.setText("Recherche");
        Btn_Search.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setText("Recherche par :");

        Rdo_Num_Emp.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Num_Emp.setSelected(true);
        Rdo_Num_Emp.setText("Num. Emp.");
        Rdo_Num_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Num_EmpActionPerformed(evt);
            }
        });

        Rdo_Name_Project.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Name_Project.setText("Nom. Projet");
        Rdo_Name_Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Name_ProjectActionPerformed(evt);
            }
        });

        Table_Work_On.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Table_Work_On.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro Employé", "Nom Employé", "Numéro Projet", "Nom Projet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Work_On.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_Work_OnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Work_On);

        Rdo_Num_Project.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Rdo_Num_Project.setText("Num. Projet");
        Rdo_Num_Project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rdo_Num_ProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Combo_Emp, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(Combo_Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(32, 32, 32)
                                        .addComponent(Rdo_Num_Emp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(Rdo_Name_Emp)
                                        .addGap(30, 30, 30)
                                        .addComponent(Rdo_Num_Project)
                                        .addGap(31, 31, 31)
                                        .addComponent(Rdo_Name_Project, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Txt_Search)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(465, 465, 465))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rdo_Num_Emp)
                    .addComponent(Rdo_Name_Emp)
                    .addComponent(jLabel2)
                    .addComponent(Rdo_Num_Project)
                    .addComponent(Rdo_Name_Project))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Combo_Emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Combo_Project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_All, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        Employee emp = new Employee();
        Project proj2 = new Project();
        
        Work_On wOn = new Work_On();
    
//-------------------------------------------------------------------------------------------------
    private void Set_Values()
    {
        
        
        String Emp_Name = Combo_Emp.getSelectedItem().toString(); // cherchons Emp_NO on donnant le nom de l'employe
        String Project_Name = Combo_Project.getSelectedItem().toString();
        
        int Emp_NO = Integer.parseInt(emp.GetValue_By_Name(Emp_Name));
        int Project_NO = Integer.parseInt(proj2.GetValue_By_Name(Project_Name));

        wOn.setEmp_NO(Emp_NO);
        wOn.setProject_NO(Project_NO);

    }       
    
    
    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed

        this.dispose();
        Tools.OpenForm(new Form_Main());

    }//GEN-LAST:event_Btn_backActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed

        Set_Values();
        wOn.Add();
     

        wOn.Get_All_Rows(Table_Work_On);
        
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        
        if(Tools.Confirm_Msg(" Voulez vous vraiment supprimer le Lien WORK_ON ?! "))
        {
            Set_Values();
            wOn.Delete();
           

           wOn.Get_All_Rows(Table_Work_On);
        }
        
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FindActionPerformed

        String Str_EmpNO = (String)Tools.InputBox(" Veillez saisir le numéro de l'employé !");
        String Str_RojectNO = (String)Tools.InputBox(" Veillez saisir le numéro du projet !");
        
        int EmpNO = Integer.parseInt(Str_EmpNO);
        int ProjNO = Integer.parseInt(Str_RojectNO);

        wOn.setEmp_NO(EmpNO);
        wOn.setProject_NO(ProjNO);
        
        wOn.Get_One_Row(Table_Work_On);
      
    }//GEN-LAST:event_Btn_FindActionPerformed

    private void Btn_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AllActionPerformed

       wOn.Get_All_Rows(Table_Work_On);
      
      
    }//GEN-LAST:event_Btn_AllActionPerformed

    private void Rdo_Name_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Name_EmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Name_EmpActionPerformed

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed

        String Str_Search = "select * from work_on_data where " ;

        if(Rdo_Num_Emp.isSelected())
        {
            Str_Search += "Number";
        }
        else if(Rdo_Name_Emp.isSelected())
        {
            Str_Search += "Name";
        }
        else if(Rdo_Num_Project.isSelected())
        {
            Str_Search += "Project_NO";
        }
        else
        {
            Str_Search += "Project_Name";
        }

        Str_Search += " like '%" + Txt_Search.getText() +  "%' ;";

        wOn.Get_Custom_Rows(Str_Search, Table_Work_On);
     
    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void Rdo_Num_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Num_EmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Num_EmpActionPerformed

    private void Rdo_Name_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Name_ProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Name_ProjectActionPerformed

    private void Table_Work_OnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_Work_OnMouseClicked

        try
        {
            int row = Table_Work_On.getSelectedRow();

            String Str_EmpName =Table_Work_On.getValueAt(row, 1).toString();
            String Str_ProjectName =Table_Work_On.getValueAt(row, 3).toString();
            

            Combo_Emp.setSelectedItem(Str_EmpName);
            Combo_Project.setSelectedItem(Str_ProjectName);


        }
        catch(Exception ex)
        {
            Tools.MsgBox(ex.getMessage());
        }

    }//GEN-LAST:event_Table_Work_OnMouseClicked

    private void Rdo_Num_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rdo_Num_ProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rdo_Num_ProjectActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        data_base.Go.Fill_Combo("Employee", "EmpName", Combo_Emp);
        data_base.Go.Fill_Combo("Project", "ProjectName", Combo_Project);
        
         Btn_Group.add(Rdo_Num_Emp);
         Btn_Group.add(Rdo_Name_Emp);
         Btn_Group.add(Rdo_Num_Project);
         Btn_Group.add(Rdo_Name_Project);
         
         wOn.Get_All_Rows(Table_Work_On);
         
         Table_Work_On.getTableHeader().setReorderingAllowed(false);
         

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Work_On.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Work_On.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Work_On.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Work_On.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Work_On().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton Btn_Add;
    private controls.JMyButton Btn_All;
    private controls.JMyButton Btn_Delete;
    private controls.JMyButton Btn_Find;
    private javax.swing.ButtonGroup Btn_Group;
    private controls.JMyButton Btn_Search;
    private controls.JMyButton Btn_back;
    private controls.JMyCombo Combo_Emp;
    private controls.JMyCombo Combo_Project;
    private javax.swing.JRadioButton Rdo_Name_Emp;
    private javax.swing.JRadioButton Rdo_Name_Project;
    private javax.swing.JRadioButton Rdo_Num_Emp;
    private javax.swing.JRadioButton Rdo_Num_Project;
    private javax.swing.JTable Table_Work_On;
    private javax.swing.JTextField Txt_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
